title: Mon Portfolio
description: Documentation du Portfolio
theme: jekyll-theme-time-machine  # Vous pouvez choisir un autre thème
markdown: kramdown  # Utilisez kramdown pour une meilleure gestion du markdown
paginate: 5  # Pagination de 5 éléments par page
